const products = [
['Essential Oversize Tee','playeras','$499 MXN','Playera de corte amplio y estilo minimalista.'],['Street Graphic Tee','playeras','$549 MXN','Diseño gráfico inspirado en el arte urbano.'],['VANTA Hoodie','sudaderas','$899 MXN','Sudadera cómoda para tus días de ciudad.'],['Night Hoodie','sudaderas','$949 MXN','Diseño sobrio con detalles contemporáneos.'],['Cargo Relaxed','pantalones','$799 MXN','Pantalón cargo de silueta relajada.'],['Classic Wide Pants','pantalones','$749 MXN','Corte amplio para combinar con todo.'],['VANTA Cap','accesorios','$349 MXN','Gorra clásica con identidad VANTA.'],['Street Tote','accesorios','$399 MXN','Bolsa práctica para llevar tu día contigo.']
];
function mostrarAlerta(mensaje,titulo='Aviso'){const modal=document.getElementById('customAlert');if(!modal)return;document.getElementById('alertTitulo').textContent=titulo;document.getElementById('alertMensaje').textContent=mensaje;modal.style.display='flex'}
function cerrarAlerta(){const x=document.getElementById('customAlert');if(x)x.style.display='none'}
function abrirDetalle(nombre,precio,desc){document.getElementById('det-nombre').textContent=nombre;document.getElementById('det-precio').textContent=precio;document.getElementById('det-desc').textContent=desc;document.getElementById('modalDetalle').style.display='flex'}
function cerrarDetalle(){document.getElementById('modalDetalle').style.display='none'}
function cerrarSesion(){localStorage.removeItem('vantaUser');localStorage.removeItem('vantaLogged');localStorage.removeItem('vantaGuest')}
function setupCatalog(){const buttons=document.querySelectorAll('.categoria-btn');const items=document.querySelectorAll('.item-producto');const title=document.getElementById('titulo-seccion');if(!buttons.length)return;buttons.forEach(b=>b.addEventListener('click',()=>{buttons.forEach(x=>x.classList.remove('activa'));b.classList.add('activa');const cat=b.dataset.cat;items.forEach(i=>i.style.display=cat==='todas'||i.dataset.categoria===cat?'block':'none');title.textContent=b.innerText.trim()}))}
function updateAuth(){const link=document.getElementById('auth-link');if(!link)return;if(localStorage.getItem('vantaLogged')==='true'){if(localStorage.getItem('vantaGuest')==='true'){link.textContent='Mi perfil';link.href='perfil.html'}else{link.textContent='Mi perfil';link.href='perfil.html'}}else{link.textContent='Iniciar sesión';link.href='login.html'}}
document.addEventListener('DOMContentLoaded',()=>{
 setupCatalog();updateAuth();
 const contacto=document.getElementById('formContacto');if(contacto)contacto.addEventListener('submit',e=>{e.preventDefault();const m=document.getElementById('msg-exito');m.style.display='block';contacto.reset();setTimeout(()=>m.style.display='none',3000)});
 const reg=document.getElementById('formRegistro');if(reg)reg.addEventListener('submit',e=>{e.preventDefault();const p=document.getElementById('reg-password').value,c=document.getElementById('reg-confirmar').value;if(p!==c){document.getElementById('registro-msg').textContent='Las contraseñas no coinciden.';document.getElementById('registro-msg').style.color='#c0392b';return}const user={nombre:document.getElementById('reg-nombre').value.trim(),correo:document.getElementById('reg-correo').value.trim(),password:p};localStorage.setItem('vantaUser',JSON.stringify(user));localStorage.setItem('vantaLogged','true');mostrarAlerta('Tu cuenta fue creada correctamente. Ahora puedes continuar a tu perfil.','¡Registro exitoso!');setTimeout(()=>location.href='perfil.html',1800)});
 const login=document.getElementById('formLogin');if(login)login.addEventListener('submit',e=>{e.preventDefault();const saved=JSON.parse(localStorage.getItem('vantaUser')||'null');const correo=document.getElementById('login-correo').value.trim(),pass=document.getElementById('login-password').value,msg=document.getElementById('login-msg');if(!correo&&!pass){localStorage.removeItem('vantaUser');localStorage.setItem('vantaLogged','true');localStorage.setItem('vantaGuest','true');msg.textContent='Entraste como invitado. Redirigiendo...';msg.style.color='green';setTimeout(()=>location.href='inicio.html',500);return}if(saved&&saved.correo===correo&&saved.password===pass){localStorage.setItem('vantaLogged','true');localStorage.removeItem('vantaGuest');msg.textContent='Inicio de sesión exitoso. Redirigiendo...';msg.style.color='green';setTimeout(()=>location.href='perfil.html',500)}else{msg.textContent='Si no tienes cuenta, deja los campos vacíos y entra como invitado.';msg.style.color='#c0392b'}});
 const invitado=document.getElementById('btnInvitado');if(invitado)invitado.addEventListener('click',()=>{localStorage.removeItem('vantaUser');localStorage.setItem('vantaLogged','true');localStorage.setItem('vantaGuest','true');const msg=document.getElementById('login-msg');if(msg){msg.textContent='Entraste como invitado. Redirigiendo...';msg.style.color='green'}setTimeout(()=>location.href='inicio.html',500)});
 const pn=document.getElementById('perfil-nombre');if(pn){const u=JSON.parse(localStorage.getItem('vantaUser')||'null');if(localStorage.getItem('vantaGuest')==='true'){pn.textContent='¡Hola, Invitado!';document.getElementById('perfil-correo').textContent='Navegando como invitado'}else{pn.textContent='¡Hola, '+(u?.nombre||'Usuario')+'!';document.getElementById('perfil-correo').textContent=u?.correo||'usuario@vanta.com'}}
});
